AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/NestedGroups:
  Max: 3

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 2

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'